// RouteId: 1, Counselling Dashboard
export const GET_ONBOARDED_STATUS_COUNT = "GET_ONBOARDED_STATUS_COUNT";
export const COUNSELOR_SESSION_GROUPS = "COUNSELOR_SESSION_GROUPS";
export const COUNSELOR_DASHBOARDSTATS = "COUNSELOR_DASHBOARDSTATS";
export const COUNSELOR_ONBOARDING_STATUS_TRANINGCOUNT = "COUNSELOR_ONBOARDING_STATUS_TRANINGCOUNT";
export const COUNSELOR_ONBOARDING_STATUS_REMAINCOUNT = "COUNSELOR_ONBOARDING_STATUS_REMAINCOUNT";
export const COUNSELOR_ONBOARDING_STATUS_COUNTS = "COUNSELOR_ONBOARDING_STATUS_COUNTS";
export const COUNSELOR_RUNNING_SESSIONS = "COUNSELOR_RUNNING_SESSIONS";
// ! Note In RouteId 1, I am not able to block UI, once we split APIs Access

// RouteId: 3, List, Tested in Local
export const GET_ENTITY_ACTIVATED_PLAN = "GET_ENTITY_ACTIVATED_PLAN";
export const GET_ENTITY_ACTIVATED_PLAN_DETAILS = "GET_ENTITY_ACTIVATED_PLAN_DETAILS";
export const GET_ENTITY_FILTER = "GET_ENTITY_FILTER";
export const POST_ENTITY_VERIFY = "POST_ENTITY_VERIFY";
export const GET_ENTITY_DETAIL = "GET_ENTITY_DETAIL";
export const GET_ENTITY_LIST = "GET_ENTITY_LIST";

// RouteId: 5, UserList, Tested in Local
export const POST_INTERNAL_USERS = "POST_INTERNAL_USERS";
export const GET_INTERNAL_USERS = "GET_INTERNAL_USERS";
export const GET_INTERNAL_USERS_DETAILS = "GET_INTERNAL_USERS_DETAILS";
export const GET_EXTERNAL_USERS = "GET_EXTERNAL_USERS";

// RouteId: 6, Premium Users List, Tested in Local
export const GET_ACTIVE_USERS = "GET_ACTIVE_USERS";
export const GET_ACTIVE_USERS_EXPIRED = "GET_ACTIVE_USERS_EXPIRED";

// RouteId: 8, Counsellor Onboarding
export const GET_ALL_CSC_LIST = "GET_ALL_CSC_LIST";
export const GET_DOCUMENT_DETALIS = "GET_DOCUMENT_DETALIS"; // done
export const POST_DOCUMENT_DETALIS = "POST_DOCUMENT_DETALIS";
export const POST_COMMERCIAL_CREATE = "POST_COMMERCIAL_CREATE";
export const GET_COMMERCIAL = "GET_COMMERCIAL"; // done
export const POST_CSC_INTERVIEW_FEEDBACK = "POST_CSC_INTERVIEW_FEEDBACK";
export const GET_CSC_INTERVIEW_FEEDBACK = "GET_CSC_INTERVIEW_FEEDBACK";
export const CSC_TEST_REPORT = "CSC_TEST_REPORT"; // done
export const PUT_VOID_BILL = "PUT_VOID_BILL";
export const GET_CSC_DETAILS = "GET_CSC_DETAILS";
export const PUT_USER_DETAILS = "PUT_USER_DETAILS";
export const PUT_INVENTORY = "PUT_INVENTORY";
export const GET_CSC_AVAILABILITY = "GET_CSC_AVAILABILITY"; // Not able fixed, where we can block this
export const AVAILABILITY_EXCEPTION = "AVAILABILITY_EXCEPTION"; // Done

// RouteId: 9, Counsellors
export const GET_CSC_LISTS = "GET_CSC_LISTS"; // List of CSC
export const GET_OVERVIEW = "GET_OVERVIEW"; 
export const GET_COUNSELOR_PERFORMANCE = "GET_COUNSELOR_PERFORMANCE";
export const GET_COUNSELOR_LEARNERS = "GET_COUNSELOR_LEARNERS";
export const GET_COUNSELOR_FEEDBACK = "GET_COUNSELOR_FEEDBACK";
// RouteId: 10, Sessions List
export const GET_SESSIONLIST = "GET_SESSIONLIST";

// RouteId: 11, Counselor Occupancy
export const GET_CSC_OCCUPANCY = "GET_CSC_OCCUPANCY";
// RouteId: 13, Session Slots Override
export const DELETE_UNIVERSAL_OVERRIDE = "DELETE_UNIVERSAL_OVERRIDE"; // Done
export const GET_UNIVERSAL_OVERRIDE = "GET_UNIVERSAL_OVERRIDE";
export const POST_UNIVERSAL_OVERRIDE = "POST_UNIVERSAL_OVERRIDE"; // Done

// RouteId: 14, Session Availability
export const GET_GLOBAL_AVAILIBILITY = "GET_GLOBAL_AVAILIBILITY";
// RouteId: 16, Item List
export const CREATE_ITEM = "CREATE_ITEM"; // Done
export const GET_ITEM_LIST = "GET_ITEM_LIST";

// RouteId: 17, Interviewers List
export const DELETE_CSC_INTERVIEWER = "DELETE_CSC_INTERVIEWER"; // Done
export const POST_CSC_INTERVIEWER = "POST_CSC_INTERVIEWER"; // Done
export const GET_CSC_INTERVIEWER_DETAILS = "GET_CSC_INTERVIEWER_DETAILS";
export const GET_CSC_INTERVIEWER_ACTIVE = "GET_CSC_INTERVIEWER_ACTIVE";
export const GET_CSC_INTERVIEWER = "GET_CSC_INTERVIEWER";

// RouteId: 21, User Role
export const GET_ALL_SYSTEM_APIS = "GET_ALL_SYSTEM_APIS";
export const PATCH_ROLE_APIS = "PATCH_ROLE_APIS";
export const GET_ALLOCATED_APIS_BYID = "GET_ALLOCATED_APIS_BYID";
export const GET_ALL_MASTER_APIS = "GET_ALL_MASTER_APIS";
export const GET_ALL_ROLES = "GET_ALL_ROLES";
export const PATCH_ROLE_ROUTE = "PATCH_ROLE_ROUTE";
export const POST_ROLE_MAP_ROUTE = "POST_ROLE_MAP_ROUTE";

// RouteId: 25, Region
export const PATCH_REGION = "PATCH_REGION"; // Done
export const DELETE_REGION = "DELETE_REGION"; // Done
export const POST_REGION = "POST_REGION"; // Done
export const GET_REGION = "GET_REGION";

// RouteId: 26, City 
export const GET_CITY = "GET_CITY";
export const DELETE_CITY = "DELETE_CITY"; // Done
export const POST_CITY = "POST_CITY"; // Done
export const PATCH_CITY = "PATCH_CITY"; // Done

// RouteId:27, VPA
export const PATCH_VPA = "PATCH_VPA"; // Done
export const DELETE_VPA = "DELETE_VPA"; // Done
export const POST_VPA = "POST_VPA"; // Done
export const GET_VPA_DETAILS = "GET_VPA_DETAILS";
export const GET_VPA_LIST = "GET_CITY";

// RouteId:28, Offers
export const PATCH_COUPON = "PATCH_COUPON"; // Done
export const DELETE_COUPON = "DELETE_COUPON"; // Done
export const POST_COUPON_MAPREGION = "POST_COUPON_MAPREGION"; 
export const POST_COUPON = "POST_COUPON"; // Done
export const GET_COUPON_DETAILS = "GET_COUPON_DETAILS"; // Done
export const GET_COUPONS = "GET_COUPONS";

// RouteId:29, Sales Meta
// RouteId:40, States
export const PATCH_MASTER_STATE = "PATCH_MASTER_STATE"; // Done
export const DELETE_MASTER_STATE = "DELETE_MASTER_STATE"; // Done
export const POST_MASTER_STATE = "POST_MASTER_STATE"; // Done
export const GET_MASTER_STATE = "GET_MASTER_STATE";
// RouteId:41, Sales Meta
export const PATCH_SELLER_META = "PATCH_SELLER_META"; // Done
export const POST_SELLER_META = "POST_SELLER_META"; // Done
export const GET_SELLER_META_LIST = "GET_SELLER_META_LIST";
export const GET_SELLER_META_DETAILS = "GET_SELLER_META_DETAILS";
export const GET_SELLERS = "GET_SELLERS";

// RouteId:51, Card Allocation
export const GET_CARD_LOT = "GET_CARD_LOT";
export const GET_CARD_LOTS = "GET_CARD_LOTS";
// RouteId:52, Financial Approval
export const GET_TRANSACTIONS_DETAILS = "GET_TRANSACTIONS_DETAILS"; // Done
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const PATCH_FINANCIAL_STATUS = "PATCH_FINANCIAL_STATUS"; // Done
// RouteId: 100, Api Master -- Total 16 Routes pending
export const DELETE_SYSTEM_APIS = "DELETE_SYSTEM_APIS"; // Done
export const GET_SYSTEM_APIS = "GET_SYSTEM_APIS";
export const PUT_SYSTEM_APIS = "PUT_SYSTEM_APIS"; // Done
export const POST_SYSTEM_APIS = "POST_SYSTEM_APIS"; // Done
export const GET_SYSTEM_APIS_BYID = "GET_SYSTEM_APIS_BYID";

// RouteId: 24, Ranking Org
export const EXPORT_RANK_ALL = "EXPORT_RANK_ALL"; // Done
export const EXPORT_RANK = "EXPORT_RANK"; // Done
export const IMPORT_RANK = "IMPORT_RANK"; // Done
export const DELETE_RANK = "DELETE_RANK"; // Done
export const PUT_RANK_LIST = "PUT_RANK_LIST"; // Done
export const POST_RANK_LIST = "POST_RANK_LIST"; // Done
export const GET_RANK_LIST = "GET_RANK_LIST";
export const GET_RANK_LIST_DROPDOWN = "GET_RANK_LIST_DROPDOWN";

// RouteId: 29, Discipline
export const EXPORT_DISCIPLINE_ALL = "EXPORT_DISCIPLINE_ALL"; // Done
export const EXPORT_DISCIPLINE = "EXPORT_DISCIPLINE"; // Done
export const IMPORT_DISCIPLINE = "IMPORT_DISCIPLINE"; // Done
export const DELETE_DISCIPLINE = "DELETE_DISCIPLINE"; // Done
export const PUT_DISCIPLINE_LIST = "PUT_DISCIPLINE_LIST"; // Done
export const POST_DISCIPLINE_LIST = "POST_DISCIPLINE_LIST"; // Done
export const GET_DISCIPLINE_LIST = "GET_DISCIPLINE_LIST";
export const GET_DISCIPLINE_LIST_DROPDOWN = "GET_DISCIPLINE_LIST_DROPDOWN";

// RouteId: 30, Academic

export const EXPORT_ACADEMIC_ALL = "EXPORT_ACADEMIC_ALL"; // Done
export const EXPORT_ACADEMIC = "EXPORT_ACADEMIC"; // Done
export const IMPORT_ACADEMIC = "IMPORT_ACADEMIC"; // Done
export const DELETE_ACADEMIC = "DELETE_ACADEMIC"; // Done
export const PUT_ACADEMIC_LIST = "PUT_ACADEMIC_LIST"; // Done
export const POST_ACADEMIC_LIST = "POST_ACADEMIC_LIST"; // Done
export const GET_ACADEMIC_LIST = "GET_ACADEMIC_LIST";

// RouteId: 31, Program
export const EXPORT_PROGRAM_ALL = "EXPORT_PROGRAM_ALL"; // Done
export const EXPORT_PROGRAM = "EXPORT_PROGRAM"; // Done
export const IMPORT_PROGRAM = "IMPORT_PROGRAM"; // Done
export const DELETE_PROGRAM = "DELETE_PROGRAM"; // Done
export const PUT_PROGRAM_LIST = "PUT_PROGRAM_LIST"; // Done
export const POST_PROGRAM_LIST = "POST_PROGRAM_LIST"; // Done
export const GET_PROGRAM_LIST = "GET_PROGRAM_LIST"; 

// RouteId: 37, Publisher Master
export const EXPORT_PUBLISHER_ALL = "EXPORT_PUBLISHER_ALL"; // Done
export const EXPORT_PUBLISHER = "EXPORT_PUBLISHER"; // Done
export const IMPORT_PUBLISHER = "IMPORT_PUBLISHER"; // Done
export const DELETE_PUBLISHER = "DELETE_PUBLISHER"; // Done
export const PUT_PUBLISHER_LIST = "PUT_PUBLISHER_LIST"; // Done
export const POST_PUBLISHER_LIST = "POST_PUBLISHER_LIST"; // Done
export const GET_PUBLISHER_LIST = "GET_PUBLISHER_LIST";
export const GET_PUBLISHER_LIST_DROPDOWN = "GET_PUBLISHER_LIST_DROPDOWN";

// RouteId: 43, Category
export const EXPORT_CATEGORY_ALL = "EXPORT_CATEGORY_ALL"; // Done
export const EXPORT_CATEGORY = "EXPORT_CATEGORY"; // Done
export const IMPORT_CATEGORY = "IMPORT_CATEGORY"; // Done
export const DELETE_CATEGORY = "DELETE_CATEGORY"; // Done
export const PUT_CATEGORY_LIST = "PUT_CATEGORY_LIST"; // Done
export const POST_CATEGORY_LIST = "POST_CATEGORY_LIST"; // Done
export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST"; 

// RouteId: 50, Accomodation Type
export const EXPORT_ACCOMODATION_TYPE_ALL = "EXPORT_ACCOMODATION_TYPE_ALL"; // Done
export const EXPORT_ACCOMODATION_TYPE = "EXPORT_ACCOMODATION_TYPE"; // Done
export const IMPORT_ACCOMODATION_TYPE = "IMPORT_ACCOMODATION_TYPE"; // Done
export const DELETE_ACCOMODATION_TYPE = "DELETE_ACCOMODATION_TYPE"; // Done
export const PUT_ACCOMODATION_TYPE_LIST = "PUT_ACCOMODATION_TYPE_LIST"; // Done
export const POST_ACCOMODATION_TYPE_LIST = "POST_ACCOMODATION_TYPE_LIST"; // Done
export const GET_ACCOMODATION_TYPE_LIST = "GET_ACCOMODATION_TYPE_LIST"; 
export const GET_ACCOMODATION_TYPE_LIST_DROPDOWN = "GET_ACCOMODATION_TYPE_LIST_DROPDOWN"; 

// RouteId: 59, Accrediation
export const EXPORT_ACCREDIATION_ALL = "EXPORT_ACCREDIATION_ALL"; // Done
export const EXPORT_ACCREDIATION = "EXPORT_ACCREDIATION"; // Done
export const IMPORT_ACCREDIATION = "IMPORT_ACCREDIATION"; // Done
export const DELETE_ACCREDIATION = "DELETE_ACCREDIATION"; // Done
export const PUT_ACCREDIATION_LIST = "PUT_ACCREDIATION_LIST"; // Done
export const POST_ACCREDIATION_LIST = "POST_ACCREDIATION_LIST"; // Done
export const GET_ACCREDIATION_LIST = "GET_ACCREDIATION_LIST"; 
export const GET_ACCREDIATION_LIST_DROPDOWN = "GET_ACCREDIATION_LIST_DROPDOWN"; 

// RouteId: 60, Affiliation
export const EXPORT_AFFILIATION_ALL = "EXPORT_AFFILIATION_ALL"; // Done
export const EXPORT_AFFILIATION = "EXPORT_AFFILIATION"; // Done
export const IMPORT_AFFILIATION = "IMPORT_AFFILIATION"; // Done
export const DELETE_AFFILIATION = "DELETE_AFFILIATION"; // Done
export const PUT_AFFILIATION_LIST = "PUT_AFFILIATION_LIST"; // Done
export const POST_AFFILIATION_LIST = "POST_AFFILIATION_LIST"; // Done
export const GET_AFFILIATION_LIST = "GET_AFFILIATION_LIST";
export const GET_AFFILIATION_LIST_DROPDOWN = "GET_AFFILIATION_LIST_DROPDOWN"; 

// RouteId: 61, City
export const EXPORT_CITY_ALL = "EXPORT_CITY_ALL"; // Done
export const EXPORT_CITY = "EXPORT_CITY"; // Done
export const IMPORT_CITY = "IMPORT_CITY"; // Done
export const DELETE_CITY_LIST = "DELETE_CITY_LIST"; // Done
export const PUT_CITY_LIST = "PUT_CITY_LIST"; // Done
export const POST_CITY_LIST = "POST_CITY_LIST"; // Done
export const GET_CITY_LIST = "GET_CITY_LIST";
export const GET_CITY_LIST_DROPDOWN = "GET_CITY_LIST_DROPDOWN"; 

// RouteId: 63, Degree
export const EXPORT_DEGREE_ALL = "EXPORT_DEGREE_ALL"; // Done
export const EXPORT_DEGREE = "EXPORT_DEGREE"; // Done
export const IMPORT_DEGREE = "IMPORT_DEGREE"; // Done
export const DELETE_DEGREE = "DELETE_DEGREE"; // Done
export const PUT_DEGREE_LIST = "PUT_DEGREE_LIST"; // Done
export const POST_DEGREE_LIST = "POST_DEGREE_LIST"; // Done
export const GET_DEGREE_LIST = "GET_DEGREE_LIST"; 

// RouteId: 64, Stream
export const EXPORT_STREAM_ALL = "EXPORT_STREAM_ALL"; // Done
export const EXPORT_STREAM = "EXPORT_STREAM"; // Done
export const IMPORT_STREAM = "IMPORT_STREAM"; // Done
export const DELETE_STREAM = "DELETE_STREAM"; // Done
export const PUT_STREAM_LIST = "PUT_STREAM_LIST"; // Done
export const POST_STREAM_LIST = "POST_STREAM_LIST"; // Done
export const GET_STREAM_LIST = "GET_STREAM_LIST"; 
export const GET_STREAM_LIST_DROPDOWN = "GET_STREAM_LIST_DROPDOWN"; 
// RouteId: 65, Subject
export const EXPORT_SUBJECT_ALL = "EXPORT_SUBJECT_ALL"; // Done
export const EXPORT_SUBJECT = "EXPORT_SUBJECT"; // Done
export const IMPORT_SUBJECT = "IMPORT_SUBJECT"; // Done
export const DELETE_SUBJECT = "DELETE_SUBJECT"; // Done
export const PUT_SUBJECT_LIST = "PUT_SUBJECT_LIST"; // Done
export const POST_SUBJECT_LIST = "POST_SUBJECT_LIST"; // Done
export const GET_SUBJECT_LIST = "GET_SUBJECT_LIST"; 
export const GET_SUBJECT_LIST_DROPDOWN = "GET_SUBJECT_LIST_DROPDOWN"; 
// RouteId: 66, Task Stmt
export const EXPORT_TASKS_ALL = "EXPORT_TASKS_ALL"; // Done
export const EXPORT_TASKS = "EXPORT_TASKS"; // Done
export const IMPORT_TASKS = "IMPORT_TASKS"; // Done
export const DELETE_TASKS = "DELETE_TASKS"; // Done
export const PUT_TASKS_LIST = "PUT_TASKS_LIST"; // Done
export const POST_TASKS_LIST = "POST_TASKS_LIST"; // Done
export const GET_TASKS_LIST = "GET_TASKS_LIST";
export const GET_TASKS_LIST_DROPDOWN = "GET_TASKS_LIST_DROPDOWN";
// RouteId: 67, Employment Status
export const EXPORT_EMPLOYMENT_STATUS_ALL = "EXPORT_EMPLOYMENT_STATUS_ALL"; // Done
export const EXPORT_EMPLOYMENT_STATUS = "EXPORT_EMPLOYMENT_STATUS"; // Done
export const IMPORT_EMPLOYMENT_STATUS = "IMPORT_EMPLOYMENT_STATUS"; // Done
export const DELETE_EMPLOYMENT_STATUS = "DELETE_EMPLOYMENT_STATUS"; // Done
export const PUT_EMPLOYMENT_STATUS_LIST = "PUT_EMPLOYMENT_STATUS_LIST"; // Done
export const POST_EMPLOYMENT_STATUS_LIST = "POST_EMPLOYMENT_STATUS_LIST"; // Done
export const GET_EMPLOYMENT_STATUS_LIST = "GET_EMPLOYMENT_STATUS_LIST";
export const GET_EMPLOYMENT_STATUS_LIST_DROPDOWN = "GET_EMPLOYMENT_STATUS_LIST_DROPDOWN";

// RouteId: 98, State
export const EXPORT_STATE_ALL = "EXPORT_STATE_ALL"; // Done
export const EXPORT_STATE = "EXPORT_STATE"; // Done
export const IMPORT_STATE = "IMPORT_STATE"; // Done
export const DELETE_STATE = "DELETE_STATE"; // Done
export const PUT_STATE_LIST = "PUT_STATE_LIST"; // Done
export const POST_STATE_LIST = "POST_STATE_LIST"; // Done
export const GET_STATE_LIST = "GET_STATE_LIST";
export const GET_STATE_LIST_DROPDOWN = "GET_STATE_LIST_DROPDOWN"; 

// RouteId: 99, Country
export const EXPORT_COUNTRY_ALL = "EXPORT_COUNTRY_ALL"; // Done
export const EXPORT_COUNTRY = "EXPORT_COUNTRY"; // Done
export const IMPORT_COUNTRY = "IMPORT_COUNTRY"; // Done
export const DELETE_COUNTRY = "DELETE_COUNTRY"; // Done
export const PUT_COUNTRY_LIST = "PUT_COUNTRY_LIST"; // Done
export const POST_COUNTRY_LIST = "POST_COUNTRY_LIST"; // Done
export const GET_COUNTRY_LIST = "GET_COUNTRY_LIST";
export const GET_COUNTRY_LIST_DROPDOWN = "GET_COUNTRY_LIST_DROPDOWN";

// RouteId: 68, College 
export const EXPORT_COLLEGE_ALL = "EXPORT_COLLEGE_ALL"; // Done
export const EXPORT_COLLEGE = "EXPORT_COLLEGE"; // Done
export const IMPORT_COLLEGE = "IMPORT_COLLEGE"; // Done
export const DELETE_COLLEGE = "DELETE_COLLEGE"; // Done
export const PUT_COLLEGE_LIST = "PUT_COLLEGE_LIST"; // Done
export const POST_COLLEGE_LIST = "POST_COLLEGE_LIST"; // Done
export const GET_COLLEGE_LIST = "GET_COLLEGE_LIST";
export const GET_COLLEGE_LIST_DROPDOWN = "GET_COLLEGE_LIST_DROPDOWN";
// RouteId: 69, College Event
export const EXPORT_COLLEGE_EVENT_ALL = "EXPORT_COLLEGE_EVENT_ALL"; // Done
export const EXPORT_COLLEGE_EVENT = "EXPORT_COLLEGE_EVENT"; // Done
export const IMPORT_COLLEGE_EVENT = "IMPORT_COLLEGE_EVENT"; // Done
export const DELETE_COLLEGE_EVENT = "DELETE_COLLEGE_EVENT"; // Done
export const PUT_COLLEGE_EVENT_LIST = "PUT_COLLEGE_EVENT_LIST"; // Done
export const POST_COLLEGE_EVENT_LIST = "POST_COLLEGE_EVENT_LIST"; // Done
export const GET_COLLEGE_EVENT_LIST = "GET_COLLEGE_EVENT_LIST";
export const GET_COLLEGE_EVENT_LIST_DROPDOWN = "GET_COLLEGE_EVENT_LIST_DROPDOWN";
// RouteId: 70, College Event Dates
export const EXPORT_COLLEGE_EVENTDATES_ALL = "EXPORT_COLLEGE_EVENTDATES_ALL"; // Done
export const EXPORT_COLLEGE_EVENTDATES = "EXPORT_COLLEGE_EVENTDATES"; // Done
export const IMPORT_COLLEGE_EVENTDATES = "IMPORT_COLLEGE_EVENTDATES"; // Done
export const DELETE_COLLEGE_EVENTDATES = "DELETE_COLLEGE_EVENTDATES"; // Done
export const PUT_COLLEGE_EVENTDATES_LIST = "PUT_COLLEGE_EVENTDATES_LIST"; // Done
export const POST_COLLEGE_EVENTDATES_LIST = "POST_COLLEGE_EVENTDATES_LIST"; // Done
export const GET_COLLEGE_EVENTDATES_LIST = "GET_COLLEGE_EVENTDATES_LIST";
export const GET_COLLEGE_EVENTDATES_LIST_DROPDOWN = "GET_COLLEGE_EVENTDATES_LIST_DROPDOWN";
 // RouteId: 71, Event Type
export const EXPORT_EVENT_TYPE_ALL = "EXPORT_EVENT_TYPE_ALL"; // Done
export const EXPORT_EVENT_TYPE = "EXPORT_EVENT_TYPE"; // Done
export const IMPORT_EVENT_TYPE = "IMPORT_EVENT_TYPE"; // Done
export const DELETE_EVENT_TYPE = "DELETE_EVENT_TYPE"; // Done
export const PUT_EVENT_TYPE_LIST = "PUT_EVENT_TYPE_LIST"; // Done
export const POST_EVENT_TYPE_LIST = "POST_EVENT_TYPE_LIST"; // Done
export const GET_EVENT_TYPE_LIST = "GET_EVENT_TYPE_LIST";
export const GET_EVENT_TYPE_LIST_DROPDOWN = "GET_EVENT_TYPE_LIST_DROPDOWN";
 // RouteId: 38, Course Faq
export const EXPORT_COURSE_FAQ_ALL = "EXPORT_COURSE_FAQ_ALL"; // Done
export const EXPORT_COURSE_FAQ = "EXPORT_COURSE_FAQ"; // Done
export const IMPORT_COURSE_FAQ = "IMPORT_COURSE_FAQ"; // Done
export const DELETE_COURSE_FAQ = "DELETE_COURSE_FAQ"; // Done
export const PUT_COURSE_FAQ_LIST = "PUT_COURSE_FAQ_LIST"; // Done
export const POST_COURSE_FAQ_LIST = "POST_COURSE_FAQ_LIST"; // Done
export const GET_COURSE_FAQ_LIST = "GET_COURSE_FAQ_LIST"; 

 // RouteId: 39, Course Asset
export const EXPORT_COURSE_ASSET_ALL = "EXPORT_COURSE_ASSET_ALL"; // Done
export const EXPORT_COURSE_ASSET = "EXPORT_COURSE_ASSET"; // Done
export const IMPORT_COURSE_ASSET = "IMPORT_COURSE_ASSET"; // Done
export const DELETE_COURSE_ASSET = "DELETE_COURSE_ASSET"; // Done
export const PUT_COURSE_ASSET_LIST = "PUT_COURSE_ASSET_LIST"; // Done
export const POST_COURSE_ASSET_LIST = "POST_COURSE_ASSET_LIST"; // Done
export const GET_COURSE_ASSET_LIST = "GET_COURSE_ASSET_LIST";
// RouteId: 44, Section Content
export const EXPORT_SECTION_CONTENT_ALL = "EXPORT_SECTION_CONTENT_ALL"; // Done
export const EXPORT_SECTION_CONTENT = "EXPORT_SECTION_CONTENT"; // Done
export const IMPORT_SECTION_CONTENT = "IMPORT_SECTION_CONTENT"; // Done
export const DELETE_SECTION_CONTENT = "DELETE_SECTION_CONTENT"; // Done
export const PUT_SECTION_CONTENT_LIST = "PUT_SECTION_CONTENT_LIST"; // Done
export const POST_SECTION_CONTENT_LIST = "POST_SECTION_CONTENT_LIST"; // Done
export const GET_SECTION_CONTENT_LIST = "GET_SECTION_CONTENT_LIST";
 // RouteId: 45, Course Section
export const EXPORT_COURSE_SECTION_ALL = "EXPORT_COURSE_SECTION_ALL"; // Done
export const EXPORT_COURSE_SECTION = "EXPORT_COURSE_SECTION"; // Done
export const IMPORT_COURSE_SECTION = "IMPORT_COURSE_SECTION"; // Done
export const DELETE_COURSE_SECTION = "DELETE_COURSE_SECTION"; // Done
export const PUT_COURSE_SECTION_LIST = "PUT_COURSE_SECTION_LIST"; // Done
export const POST_COURSE_SECTION_LIST = "POST_COURSE_SECTION_LIST"; // Done
export const GET_COURSE_SECTION_LIST = "GET_COURSE_SECTION_LIST";
 // RouteId: 46, Course Details
export const EXPORT_COURSE_DETAILS_ALL = "EXPORT_COURSE_DETAILS_ALL"; // Done
export const EXPORT_COURSE_DETAILS = "EXPORT_COURSE_DETAILS"; // Done
export const IMPORT_COURSE_DETAILS = "IMPORT_COURSE_DETAILS"; // Done
export const DELETE_COURSE_DETAILS = "DELETE_COURSE_DETAILS"; // Done
export const PUT_COURSE_DETAILS_LIST = "PUT_COURSE_DETAILS_LIST"; // Done
export const POST_COURSE_DETAILS_LIST = "POST_COURSE_DETAILS_LIST"; // Done
export const GET_COURSE_DETAILS_LIST = "GET_COURSE_DETAILS_LIST"; 
 // RouteId: 72, Entity Courses
export const EXPORT_COURSES_ENTITY_ALL = "EXPORT_COURSES_ENTITY_ALL"; // Done
export const EXPORT_COURSES_ENTITY = "EXPORT_COURSES_ENTITY"; // Done
export const IMPORT_COURSES_ENTITY = "IMPORT_COURSES_ENTITY"; // Done
export const DELETE_COURSES_ENTITY = "DELETE_COURSES_ENTITY"; // Done
export const PUT_COURSES_ENTITY_LIST = "PUT_COURSES_ENTITY_LIST"; // Done
export const POST_COURSES_ENTITY_LIST = "POST_COURSES_ENTITY_LIST"; // Done
export const GET_COURSES_ENTITY_LIST = "GET_COURSES_ENTITY_LIST";
// RouteId:73, Course Eligibility 
export const EXPORT_COURSE_ELIGIBILITY_ALL = "EXPORT_COURSE_ELIGIBILITY_ALL"; // Done
export const EXPORT_COURSE_ELIGIBILITY = "EXPORT_COURSE_ELIGIBILITY"; // Done
export const IMPORT_COURSE_ELIGIBILITY = "IMPORT_COURSE_ELIGIBILITY"; // Done
export const DELETE_COURSE_ELIGIBILITY = "DELETE_COURSE_ELIGIBILITY"; // Done
export const PUT_COURSE_ELIGIBILITY_LIST = "PUT_COURSE_ELIGIBILITY_LIST"; // Done
export const POST_COURSE_ELIGIBILITY_LIST = "POST_COURSE_ELIGIBILITY_LIST"; // Done
export const GET_COURSE_ELIGIBILITY_LIST = "GET_COURSE_ELIGIBILITY_LIST";
 // RouteId:74, Course Examination 
export const EXPORT_COURSE_EXAMINATION_ALL = "EXPORT_COURSE_EXAMINATION_ALL"; // Done
export const EXPORT_COURSE_EXAMINATION = "EXPORT_COURSE_EXAMINATION"; // Done
export const IMPORT_COURSE_EXAMINATION = "IMPORT_COURSE_EXAMINATION"; // Done
export const DELETE_COURSE_EXAMINATION = "DELETE_COURSE_EXAMINATION"; // Done
export const PUT_COURSE_EXAMINATION_LIST = "PUT_COURSE_EXAMINATION_LIST"; // Done
export const POST_COURSE_EXAMINATION_LIST = "POST_COURSE_EXAMINATION_LIST"; // Done
export const GET_COURSE_EXAMINATION_LIST = "GET_COURSE_EXAMINATION_LIST";
 // RouteId:75, Course Master
export const EXPORT_COURSE_CAREER_DETAILS_ALL = "EXPORT_COURSE_CAREER_DETAILS_ALL"; // Done
export const EXPORT_COURSE_CAREER_DETAILS = "EXPORT_COURSE_CAREER_DETAILS"; // Done
export const IMPORT_COURSE_CAREER_DETAILS = "IMPORT_COURSE_CAREER_DETAILS"; // Done
export const DELETE_COURSE_CAREER_DETAILS = "DELETE_COURSE_CAREER_DETAILS"; // Done
export const PUT_COURSE_CAREER_DETAILS_LIST = "PUT_COURSE_CAREER_DETAILS_LIST"; // Done
export const POST_COURSE_CAREER_DETAILS_LIST = "POST_COURSE_CAREER_DETAILS_LIST"; // Done
export const GET_COURSE_CAREER_DETAILS_LIST = "GET_COURSE_CAREER_DETAILS_LIST";
// RouteId:76, Course Level Master
export const EXPORT_CAREER_COURSE_LEVEL_ALL = "EXPORT_CAREER_COURSE_LEVEL_ALL"; // Done
export const EXPORT_CAREER_COURSE_LEVEL = "EXPORT_CAREER_COURSE_LEVEL"; // Done
export const IMPORT_CAREER_COURSE_LEVEL = "IMPORT_CAREER_COURSE_LEVEL"; // Done
export const DELETE_CAREER_COURSE_LEVEL = "DELETE_CAREER_COURSE_LEVEL"; // Done
export const PUT_CAREER_COURSE_LEVEL_LIST = "PUT_CAREER_COURSE_LEVEL_LIST"; // Done
export const POST_CAREER_COURSE_LEVEL_LIST = "POST_CAREER_COURSE_LEVEL_LIST"; // Done
export const GET_CAREER_COURSE_LEVEL_LIST = "GET_CAREER_COURSE_LEVEL_LIST";
// RouteId:77, Course Type Master
export const EXPORT_COURSETYPE_ALL = "EXPORT_COURSETYPE_ALL"; // Done
export const EXPORT_COURSETYPE = "EXPORT_COURSETYPE"; // Done
export const IMPORT_COURSETYPE = "IMPORT_COURSETYPE"; // Done
export const DELETE_COURSETYPE = "DELETE_COURSETYPE"; // Done
export const PUT_COURSETYPE_LIST = "PUT_COURSETYPE_LIST"; // Done
export const POST_COURSETYPE_LIST = "POST_COURSETYPE_LIST"; // Done
export const GET_COURSETYPE_LIST = "GET_COURSETYPE_LIST";
 // RouteId:78, Entity Master
export const EXPORT_MASTER_ENTITY_ALL = "EXPORT_MASTER_ENTITY_ALL"; // Done
export const EXPORT_MASTER_ENTITY = "EXPORT_MASTER_ENTITY"; // Done
export const IMPORT_MASTER_ENTITY = "IMPORT_MASTER_ENTITY"; // Done
export const DELETE_MASTER_ENTITY = "DELETE_MASTER_ENTITY"; // Done
export const PUT_MASTER_ENTITY_LIST = "PUT_MASTER_ENTITY_LIST"; // Done
export const POST_MASTER_ENTITY_LIST = "POST_MASTER_ENTITY_LIST"; // Done
export const GET_MASTER_ENTITY_LIST = "GET_MASTER_ENTITY_LIST";
export const GET_MASTER_ENTITY_LIST_DROPDOWMN = "GET_MASTER_ENTITY_LIST_DROPDOWMN";
// RouteId:79, Accomodation Mapper
export const EXPORT_ACCOMODATION_ALL = "EXPORT_ACCOMODATION_ALL"; // Done
export const EXPORT_ACCOMODATION = "EXPORT_ACCOMODATION"; // Done
export const IMPORT_ACCOMODATION = "IMPORT_ACCOMODATION"; // Done
export const DELETE_ACCOMODATION = "DELETE_ACCOMODATION"; // Done
export const PUT_ACCOMODATION_LIST = "PUT_ACCOMODATION_LIST"; // Done
export const POST_ACCOMODATION_LIST = "POST_ACCOMODATION_LIST"; // Done
export const GET_ACCOMODATION_LIST = "GET_ACCOMODATION_LIST";
// RouteId:80, Accreditation Mapper
export const EXPORT_ACCREDITATION_MAPPER_ALL = "EXPORT_ACCREDITATION_MAPPER_ALL"; // Done
export const EXPORT_ACCREDITATION_MAPPER = "EXPORT_ACCREDITATION_MAPPER"; // Done
export const IMPORT_ACCREDITATION_MAPPER = "IMPORT_ACCREDITATION_MAPPER"; // Done
export const DELETE_ACCREDITATION_MAPPER = "DELETE_ACCREDITATION_MAPPER"; // Done
export const PUT_ACCREDITATION_MAPPER_LIST = "PUT_ACCREDITATION_MAPPER_LIST"; // Done
export const POST_ACCREDITATION_MAPPER_LIST = "POST_ACCREDITATION_MAPPER_LIST"; // Done
export const GET_ACCREDITATION_MAPPER_LIST = "GET_ACCREDITATION_MAPPER_LIST";    

// RouteId:81, Campus Entity -------
export const EXPORT_CAMPUS_ALL = "EXPORT_CAMPUS_ALL"; // Done
export const EXPORT_CAMPUS = "EXPORT_CAMPUS"; // Done
export const IMPORT_CAMPUS = "IMPORT_CAMPUS"; // Done
export const DELETE_CAMPUS = "DELETE_CAMPUS"; // Done
export const PUT_CAMPUS_LIST = "PUT_CAMPUS_LIST"; // Done
export const POST_CAMPUS_LIST = "POST_CAMPUS_LIST"; // Done
export const GET_CAMPUS_LIST = "GET_CAMPUS_LIST";
 // RouteId:82, Ranking Mapper Entity
export const EXPORT_RANKING_MAPPER_ALL = "EXPORT_RANKING_MAPPER_ALL"; // Done
export const EXPORT_RANKING_MAPPER = "EXPORT_RANKING_MAPPER"; // Done
export const IMPORT_RANKING_MAPPER = "IMPORT_RANKING_MAPPER"; // Done
export const DELETE_RANKING_MAPPER = "DELETE_RANKING_MAPPER"; // Done
export const PUT_RANKING_MAPPER_LIST = "PUT_RANKING_MAPPER_LIST"; // Done
export const POST_RANKING_MAPPER_LIST = "POST_RANKING_MAPPER_LIST"; // Done
export const GET_RANKING_MAPPER_LIST = "GET_RANKING_MAPPER_LIST";
// RouteId:83, Examination Master
export const EXPORT_EXAMINATION_MASTER_ALL = "EXPORT_EXAMINATION_MASTER_ALL"; // Done
export const EXPORT_EXAMINATION_MASTER = "EXPORT_EXAMINATION_MASTER"; // Done
export const IMPORT_EXAMINATION_MASTER = "IMPORT_EXAMINATION_MASTER"; // Done
export const DELETE_EXAMINATION_MASTER = "DELETE_EXAMINATION_MASTER"; // Done
export const PUT_EXAMINATION_MASTER_LIST = "PUT_EXAMINATION_MASTER_LIST"; // Done
export const POST_EXAMINATION_MASTER_LIST = "POST_EXAMINATION_MASTER_LIST"; // Done
export const GET_EXAMINATION_MASTER_LIST = "GET_EXAMINATION_MASTER_LIST";
// RouteId:84, Exams Type Master
export const EXPORT_EXAMTYPE_ALL = "EXPORT_EXAMTYPE_ALL"; // Done
export const EXPORT_EXAMTYPE = "EXPORT_EXAMTYPE"; // Done
export const IMPORT_EXAMTYPE = "IMPORT_EXAMTYPE"; // Done
export const DELETE_EXAMTYPE = "DELETE_EXAMTYPE"; // Done
export const PUT_EXAMTYPE_LIST = "PUT_EXAMTYPE_LIST"; // Done
export const POST_EXAMTYPE_LIST = "POST_EXAMTYPE_LIST"; // Done
export const GET_EXAMTYPE_LIST = "GET_EXAMTYPE_LIST";
// RouteId:85, Employment Status
export const EXPORT_OCC_EMPLOYMENT_STATUS_ALL = "EXPORT_OCC_EMPLOYMENT_STATUS_ALL"; // Done
export const EXPORT_OCC_EMPLOYMENT_STATUS = "EXPORT_OCC_EMPLOYMENT_STATUS"; // Done
export const IMPORT_OCC_EMPLOYMENT_STATUS = "IMPORT_OCC_EMPLOYMENT_STATUS"; // Done
export const DELETE_OCC_EMPLOYMENT_STATUS = "DELETE_OCC_EMPLOYMENT_STATUS"; // Done
export const PUT_OCC_EMPLOYMENT_STATUS_LIST = "PUT_OCC_EMPLOYMENT_STATUS_LIST"; // Done
export const POST_OCC_EMPLOYMENT_STATUS_LIST = "POST_OCC_EMPLOYMENT_STATUS_LIST"; // Done
export const GET_OCC_EMPLOYMENT_STATUS_LIST = "GET_OCC_EMPLOYMENT_STATUS_LIST";
export const GET_OCC_EMPLOYMENT_STATUS_LIST_DROPDOWN = "GET_OCC_EMPLOYMENT_STATUS_LIST_DROPDOWN";
// RouteId:86, Occupation Master 
export const EXPORT_OCC_ACCOMODATION_ALL = "EXPORT_OCC_ACCOMODATION_ALL"; // Done
export const EXPORT_OCC_ACCOMODATION = "EXPORT_OCC_ACCOMODATION"; // Done
export const IMPORT_OCC_ACCOMODATION = "IMPORT_OCC_ACCOMODATION"; // Done
export const DELETE_OCC_ACCOMODATION = "DELETE_OCC_ACCOMODATION"; // Done
export const PUT_OCC_ACCOMODATION_LIST = "PUT_OCC_ACCOMODATION_LIST"; // Done
export const POST_OCC_ACCOMODATION_LIST = "POST_OCC_ACCOMODATION_LIST"; // Done
export const GET_OCC_ACCOMODATION_LIST = "GET_OCC_ACCOMODATION_LIST"; // Done
// RouteId:87, Regional Occupation -- STILL NEED to Check May be Database maping wrong
// export const EXPORT_OCCUPATION_EXPENSES_ALL = "EXPORT_OCCUPATION_EXPENSES_ALL"; // Done
// export const EXPORT_OCCUPATION_EXPENSES = "EXPORT_OCCUPATION_EXPENSES"; // Done
// export const IMPORT_OCCUPATION_EXPENSES = "IMPORT_OCCUPATION_EXPENSES"; // Done
// export const DELETE_OCCUPATION_EXPENSES = "DELETE_OCCUPATION_EXPENSES"; // Done
// export const PUT_OCCUPATION_EXPENSES_LIST = "PUT_OCCUPATION_EXPENSES_LIST"; // Done
// export const POST_OCCUPATION_EXPENSES_LIST = "POST_OCCUPATION_EXPENSES_LIST"; // Done
// export const GET_OCCUPATION_EXPENSES_LIST = "GET_OCCUPATION_EXPENSES_LIST";
// RouteId:88, Benchmarkhour
export const EXPORT_OCCUPATION_BENCHMARK_ALL = "EXPORT_OCCUPATION_BENCHMARK_ALL"; // Done
export const EXPORT_OCCUPATION_BENCHMARK = "EXPORT_OCCUPATION_BENCHMARK"; // Done
export const IMPORT_OCCUPATION_BENCHMARK = "IMPORT_OCCUPATION_BENCHMARK"; // Done
export const DELETE_OCCUPATION_BENCHMARK = "DELETE_OCCUPATION_BENCHMARK"; // Done
export const PUT_OCCUPATION_BENCHMARK_LIST = "PUT_OCCUPATION_BENCHMARK_LIST"; // Done
export const POST_OCCUPATION_BENCHMARK_LIST = "POST_OCCUPATION_BENCHMARK_LIST"; // Done
export const GET_OCCUPATION_BENCHMARK_LIST = "GET_OCCUPATION_BENCHMARK_LIST";
 // RouteId:89, Course
export const EXPORT_OCCUPATION_COURSE_ALL = "EXPORT_OCCUPATION_COURSE_ALL"; // Done
export const EXPORT_OCCUPATION_COURSE = "EXPORT_OCCUPATION_COURSE"; // Done
export const IMPORT_OCCUPATION_COURSE = "IMPORT_OCCUPATION_COURSE"; // Done
export const DELETE_OCCUPATION_COURSE = "DELETE_OCCUPATION_COURSE"; // Done
export const PUT_OCCUPATION_COURSE_LIST = "PUT_OCCUPATION_COURSE_LIST"; // Done
export const POST_OCCUPATION_COURSE_LIST = "POST_OCCUPATION_COURSE_LIST"; // Done
export const GET_OCCUPATION_COURSE_LIST = "GET_OCCUPATION_COURSE_LIST";
// RouteId:90, Exam
export const EXPORT_OCCUPATION_EXAM_ALL = "EXPORT_OCCUPATION_EXAM_ALL"; // Done
export const EXPORT_OCCUPATION_EXAM = "EXPORT_OCCUPATION_EXAM"; // Done
export const IMPORT_OCCUPATION_EXAM = "IMPORT_OCCUPATION_EXAM"; // Done
export const DELETE_OCCUPATION_EXAM = "DELETE_OCCUPATION_EXAM"; // Done
export const PUT_OCCUPATION_EXAM_LIST = "PUT_OCCUPATION_EXAM_LIST"; // Done
export const POST_OCCUPATION_EXAM_LIST = "POST_OCCUPATION_EXAM_LIST"; // Done
export const GET_OCCUPATION_EXAM_LIST = "GET_OCCUPATION_EXAM_LIST";
// RouteId:91, Expenses
export const EXPORT_OCCUPATION_EXPENSES_ALL = "EXPORT_OCCUPATION_EXPENSES_ALL"; // Done
export const EXPORT_OCCUPATION_EXPENSES = "EXPORT_OCCUPATION_EXPENSES"; // Done
export const IMPORT_OCCUPATION_EXPENSES = "IMPORT_OCCUPATION_EXPENSES"; // Done
export const DELETE_OCCUPATION_EXPENSES = "DELETE_OCCUPATION_EXPENSES"; // Done
export const PUT_OCCUPATION_EXPENSES_LIST = "PUT_OCCUPATION_EXPENSES_LIST"; // Done
export const POST_OCCUPATION_EXPENSES_LIST = "POST_OCCUPATION_EXPENSES_LIST"; // Done
export const GET_OCCUPATION_EXPENSES_LIST = "GET_OCCUPATION_EXPENSES_LIST";
// RouteId:92, Meta
export const EXPORT_OCCUPATION_META_ALL = "EXPORT_OCCUPATION_META_ALL"; // Done
export const EXPORT_OCCUPATION_META = "EXPORT_OCCUPATION_META"; // Done
export const IMPORT_OCCUPATION_META = "IMPORT_OCCUPATION_META"; // Done
export const DELETE_OCCUPATION_META = "DELETE_OCCUPATION_META"; // Done
export const PUT_OCCUPATION_META_LIST = "PUT_OCCUPATION_META_LIST"; // Done
export const POST_OCCUPATION_META_LIST = "POST_OCCUPATION_META_LIST"; // Done
export const GET_OCCUPATION_META_LIST = "GET_OCCUPATION_META_LIST"; 
// RouteId:93, Progression
export const EXPORT_OCCUPATION_PROGRESSION_ALL = "EXPORT_OCCUPATION_PROGRESSION_ALL"; // Done
export const EXPORT_OCCUPATION_PROGRESSION = "EXPORT_OCCUPATION_PROGRESSION"; // Done
export const IMPORT_OCCUPATION_PROGRESSION = "IMPORT_OCCUPATION_PROGRESSION"; // Done
export const DELETE_OCCUPATION_PROGRESSION = "DELETE_OCCUPATION_PROGRESSION"; // Done
export const PUT_OCCUPATION_PROGRESSION_LIST = "PUT_OCCUPATION_PROGRESSION_LIST"; // Done
export const POST_OCCUPATION_PROGRESSION_LIST = "POST_OCCUPATION_PROGRESSION_LIST"; // Done
export const GET_OCCUPATION_PROGRESSION_LIST = "GET_OCCUPATION_PROGRESSION_LIST";
 // RouteId:94, Qualification
export const EXPORT_OCCUPATION_QUALIFICATION_ALL = "EXPORT_OCCUPATION_QUALIFICATION_ALL"; // Done
export const EXPORT_OCCUPATION_QUALIFICATION = "EXPORT_OCCUPATION_QUALIFICATION"; // Done
export const IMPORT_OCCUPATION_QUALIFICATION = "IMPORT_OCCUPATION_QUALIFICATION"; // Done
export const DELETE_OCCUPATION_QUALIFICATION = "DELETE_OCCUPATION_QUALIFICATION"; // Done
export const PUT_OCCUPATION_QUALIFICATION_LIST = "PUT_OCCUPATION_QUALIFICATION_LIST"; // Done
export const POST_OCCUPATION_QUALIFICATION_LIST = "POST_OCCUPATION_QUALIFICATION_LIST"; // Done
export const GET_OCCUPATION_QUALIFICATION_LIST = "GET_OCCUPATION_QUALIFICATION_LIST";
 // RouteId:95, Salary
export const EXPORT_SALARY_ALL = "EXPORT_SALARY_ALL"; // Done
export const EXPORT_SALARY = "EXPORT_SALARY"; // Done
export const IMPORT_SALARY = "IMPORT_SALARY"; // Done
export const DELETE_SALARY = "DELETE_SALARY"; // Done
export const PUT_SALARY_LIST = "PUT_SALARY_LIST"; // Done
export const POST_SALARY_LIST = "POST_SALARY_LIST"; // Done
export const GET_SALARY_LIST = "GET_SALARY_LIST"; 
 // RouteId:96, Study Route
export const EXPORT_STUDY_ROUTE_ALL = "EXPORT_STUDY_ROUTE_ALL"; // Done
export const EXPORT_STUDY_ROUTE = "EXPORT_STUDY_ROUTE"; // Done
export const IMPORT_STUDY_ROUTE = "IMPORT_STUDY_ROUTE"; // Done
export const DELETE_STUDY_ROUTE = "DELETE_STUDY_ROUTE"; // Done
export const PUT_STUDY_ROUTE_LIST = "PUT_STUDY_ROUTE_LIST"; // Done
export const POST_STUDY_ROUTE_LIST = "POST_STUDY_ROUTE_LIST"; // Done
export const GET_STUDY_ROUTE_LIST = "GET_STUDY_ROUTE_LIST";
 // RouteId:97, Study Route Path
 export const EXPORT_OCCUPATION_STUDYROUTEPATH_ALL = "EXPORT_OCCUPATION_STUDYROUTEPATH_ALL"; // Done
 export const EXPORT_OCCUPATION_STUDYROUTEPATH = "EXPORT_OCCUPATION_STUDYROUTEPATH"; // Done
 export const IMPORT_OCCUPATION_STUDYROUTEPATH = "IMPORT_OCCUPATION_STUDYROUTEPATH"; // Done
 export const DELETE_OCCUPATION_STUDYROUTEPATH = "DELETE_OCCUPATION_STUDYROUTEPATH"; // Done
 export const PUT_OCCUPATION_STUDYROUTEPATH_LIST = "PUT_OCCUPATION_STUDYROUTEPATH_LIST"; // Done
 export const POST_OCCUPATION_STUDYROUTEPATH_LIST = "POST_OCCUPATION_STUDYROUTEPATH_LIST"; // Done
 export const GET_OCCUPATION_STUDYROUTEPATH_LIST = "GET_OCCUPATION_STUDYROUTEPATH_LIST"; 
 
// export const Rbac = new RBAC();